### ISSUE TITLE
[iOS Bug]: Toolbar Menu - UIManager.showMenuPopup is not a function

### ISSUE THREAD

**Issue by dwilt** [xotahal/react-native-material-ui#131] opened 2017-04-18 23:53 UTC
This only happens in iOS. It works fine in Android.

While trying to click a menu button:
![image](https://cloud.githubusercontent.com/assets/1065539/25157546/e3f90faa-2456-11e7-99c4-81b3def17094.png)
with this code:
```jsx
<Toolbar
    style={{
        container: {
            backgroundColor
        }
    }}
    rightElement={{
        menu: {
            icon: `more-vert`,
            labels: [
                `Sign Out`,
                `Settings`
            ]
        }
    }}
    centerElement={companyName}
    onRightElementPress={() => console.log(`pressed`)}
/>
```
I get this:
![image](https://cloud.githubusercontent.com/assets/1065539/25157536/dae344da-2456-11e7-9119-40f6bb1b0347.png)

I've traced this line back to the [RightElement](https://github.com/xotahal/react-native-material-ui/blob/edf7505850e58b72cd442093809a67a573362cfe/src/Toolbar/RightElement.react.js#L52) and at this point, `UIManager` does not contain a method called `showPopupMenu`. Here is what it's current state is:

```json
{
  "RCTTextView": {
    "Manager": "TextViewManager",
    "NativeProps": {
      "text": "NSString",
      "color": "UIColor",
      "onTextInput": "BOOL",
      "clearTextOnFocus": "BOOL",
      "spellCheck": "UITextSpellCheckingType",
      "autoCorrect": "UITextAutocorrectionType",
      "autoCapitalize": "UITextAutocapitalizationType",
      "placeholder": "NSString",
      "onScroll": "BOOL",
      "secureTextEntry": "BOOL",
      "selection": "RCTTextSelection",
      "blurOnSubmit": "BOOL",
      "keyboardType": "UIKeyboardType",
      "onContentSizeChange": "BOOL",
      "mostRecentEventCount": "NSInteger",
      "dataDetectorTypes": "UIDataDetectorTypes",
      "onChange": "BOOL",
      "fontWeight": "NSString",
      "fontStyle": "NSString",
      "fontSize": "NSNumber",
      "fontFamily": "NSString",
      "onSelectionChange": "BOOL",
      "placeholderTextColor": "UIColor",
      "enablesReturnKeyAutomatically": "BOOL",
      "returnKeyType": "UIReturnKeyType",
      "editable": "BOOL",
      "textAlign": "NSTextAlignment",
      "keyboardAppearance": "UIKeyboardAppearance",
      "maxLength": "NSNumber",
      "selectionColor": "UIColor",
      "selectTextOnFocus": "BOOL"
    },
    "Constants": {},
    "Commands": {}
  },
  "RCTSwitch": {
    "Manager": "SwitchManager",
    "NativeProps": {
      "thumbTintColor": "UIColor",
      "tintColor": "UIColor",
      "onTintColor": "UIColor",
      "value": "BOOL",
      "onChange": "BOOL",
      "disabled": "BOOL"
    },
    "Constants": {},
    "Commands": {}
  },
  "RCTMap": {
    "Manager": "MapManager",
    "NativeProps": {
      "onAnnotationDragStateChange": "BOOL",
      "followUserLocation": "BOOL",
      "annotations": "NSArray<RCTMapAnnotation *>",
      "rotateEnabled": "BOOL",
      "onPress": "BOOL",
      "region": "MKCoordinateRegion",
      "showsUserLocation": "BOOL",
      "showsAnnotationCallouts": "BOOL",
      "minDelta": "CGFloat",
      "overlays": "NSArray<RCTMapOverlay *>",
      "showsCompass": "BOOL",
      "mapType": "MKMapType",
      "legalLabelInsets": "UIEdgeInsets",
      "scrollEnabled": "BOOL",
      "onChange": "BOOL",
      "maxDelta": "CGFloat",
      "pitchEnabled": "BOOL",
      "zoomEnabled": "BOOL",
      "onAnnotationBlur": "BOOL",
      "showsPointsOfInterest": "BOOL",
      "onAnnotationFocus": "BOOL"
    },
    "Constants": {},
    "Commands": {}
  },
  "RCTNavigator": {
    "Manager": "NavigatorManager",
    "NativeProps": {
      "interactivePopGestureEnabled": "BOOL",
      "requestedTopOfStack": "NSInteger",
      "onNavigationProgress": "BOOL",
      "onNavigationComplete": "BOOL"
    },
    "Constants": {},
    "Commands": {
      "requestSchedulingJavaScriptNavigation": 0
    }
  },
  "RCTScrollContentView": {
    "Manager": "ScrollContentViewManager",
    "NativeProps": {},
    "Constants": {},
    "Commands": {}
  },
  "RCTScrollView": {
    "Manager": "ScrollViewManager",
    "NativeProps": {
      "keyboardDismissMode": "UIScrollViewKeyboardDismissMode",
      "indicatorStyle": "UIScrollViewIndicatorStyle",
      "decelerationRate": "CGFloat",
      "onScrollEndDrag": "BOOL",
      "contentOffset": "CGPoint",
      "scrollEnabled": "BOOL",
      "alwaysBounceHorizontal": "BOOL",
      "scrollsToTop": "BOOL",
      "onMomentumScrollBegin": "BOOL",
      "automaticallyAdjustContentInsets": "BOOL",
      "alwaysBounceVertical": "BOOL",
      "onScroll": "BOOL",
      "centerContent": "BOOL",
      "scrollEventThrottle": "NSTimeInterval",
      "onMomentumScrollEnd": "BOOL",
      "snapToAlignment": "NSString",
      "bouncesZoom": "BOOL",
      "showsVerticalScrollIndicator": "BOOL",
      "stickyHeaderIndices": "NSIndexSet",
      "zoomScale": "CGFloat",
      "contentInset": "UIEdgeInsets",
      "canCancelContentTouches": "BOOL",
      "overflow": "YGOverflow",
      "scrollIndicatorInsets": "UIEdgeInsets",
      "onScrollAnimationEnd": "BOOL",
      "pagingEnabled": "BOOL",
      "minimumZoomScale": "CGFloat",
      "onScrollBeginDrag": "BOOL",
      "snapToInterval": "int",
      "maximumZoomScale": "CGFloat",
      "bounces": "BOOL",
      "directionalLockEnabled": "BOOL",
      "showsHorizontalScrollIndicator": "BOOL"
    },
    "Constants": {},
    "Commands": {
      "getContentSize": 0,
      "calculateChildFrames": 1,
      "scrollTo": 2,
      "scrollToEnd": 3,
      "zoomToRect": 4
    }
  },
  "customDirectEventTypes": {
    "topLoadingFinish": {
      "registrationName": "onLoadingFinish"
    },
    "topAccessibilityTap": {
      "registrationName": "onAccessibilityTap"
    },
    "topNavigationProgress": {
      "registrationName": "onNavigationProgress"
    },
    "topLoadStart": {
      "registrationName": "onLoadStart"
    },
    "topError": {
      "registrationName": "onError"
    },
    "topPartialLoad": {
      "registrationName": "onPartialLoad"
    },
    "topScrollBeginDrag": {
      "registrationName": "onScrollBeginDrag"
    },
    "topMomentumScrollBegin": {
      "registrationName": "onMomentumScrollBegin"
    },
    "topScrollEndDrag": {
      "registrationName": "onScrollEndDrag"
    },
    "topShouldStartLoadWithRequest": {
      "registrationName": "onShouldStartLoadWithRequest"
    },
    "topOrientationChange": {
      "registrationName": "onOrientationChange"
    },
    "topMagicTap": {
      "registrationName": "onMagicTap"
    },
    "topTextInput": {
      "registrationName": "onTextInput"
    },
    "topLoadEnd": {
      "registrationName": "onLoadEnd"
    },
    "topRefresh": {
      "registrationName": "onRefresh"
    },
    "topScrollAnimationEnd": {
      "registrationName": "onScrollAnimationEnd"
    },
    "topLoadingStart": {
      "registrationName": "onLoadingStart"
    },
    "topMessage": {
      "registrationName": "onMessage"
    },
    "topScroll": {
      "registrationName": "onScroll"
    },
    "topShow": {
      "registrationName": "onShow"
    },
    "topLoadingError": {
      "registrationName": "onLoadingError"
    },
    "topMomentumScrollEnd": {
      "registrationName": "onMomentumScrollEnd"
    },
    "topProgress": {
      "registrationName": "onProgress"
    },
    "topLoad": {
      "registrationName": "onLoad"
    },
    "topSelectionChange": {
      "registrationName": "onSelectionChange"
    },
    "topLayout": {
      "registrationName": "onLayout"
    }
  },
  "customBubblingEventTypes": {
    "topFocus": {
      "phasedRegistrationNames": {
        "bubbled": "onFocus",
        "captured": "onFocusCapture"
      }
    },
    "topTouchEnd": {
      "phasedRegistrationNames": {
        "bubbled": "onTouchEnd",
        "captured": "onTouchEndCapture"
      }
    },
    "topTouchStart": {
      "phasedRegistrationNames": {
        "bubbled": "onTouchStart",
        "captured": "onTouchStartCapture"
      }
    },
    "topBlur": {
      "phasedRegistrationNames": {
        "bubbled": "onBlur",
        "captured": "onBlurCapture"
      }
    },
    "topEndEditing": {
      "phasedRegistrationNames": {
        "bubbled": "onEndEditing",
        "captured": "onEndEditingCapture"
      }
    },
    "topAnnotationDragStateChange": {
      "phasedRegistrationNames": {
        "bubbled": "onAnnotationDragStateChange",
        "captured": "onAnnotationDragStateChangeCapture"
      }
    },
    "topTouchMove": {
      "phasedRegistrationNames": {
        "bubbled": "onTouchMove",
        "captured": "onTouchMoveCapture"
      }
    },
    "topSubmitEditing": {
      "phasedRegistrationNames": {
        "bubbled": "onSubmitEditing",
        "captured": "onSubmitEditingCapture"
      }
    },
    "topAnnotationBlur": {
      "phasedRegistrationNames": {
        "bubbled": "onAnnotationBlur",
        "captured": "onAnnotationBlurCapture"
      }
    },
    "topChange": {
      "phasedRegistrationNames": {
        "bubbled": "onChange",
        "captured": "onChangeCapture"
      }
    },
    "topKeyPress": {
      "phasedRegistrationNames": {
        "bubbled": "onKeyPress",
        "captured": "onKeyPressCapture"
      }
    },
    "topNavigationComplete": {
      "phasedRegistrationNames": {
        "bubbled": "onNavigationComplete",
        "captured": "onNavigationCompleteCapture"
      }
    },
    "topRightButtonPress": {
      "phasedRegistrationNames": {
        "bubbled": "onRightButtonPress",
        "captured": "onRightButtonPressCapture"
      }
    },
    "topLeftButtonPress": {
      "phasedRegistrationNames": {
        "bubbled": "onLeftButtonPress",
        "captured": "onLeftButtonPressCapture"
      }
    },
    "topSlidingComplete": {
      "phasedRegistrationNames": {
        "bubbled": "onSlidingComplete",
        "captured": "onSlidingCompleteCapture"
      }
    },
    "topPress": {
      "phasedRegistrationNames": {
        "bubbled": "onPress",
        "captured": "onPressCapture"
      }
    },
    "topAnnotationFocus": {
      "phasedRegistrationNames": {
        "bubbled": "onAnnotationFocus",
        "captured": "onAnnotationFocusCapture"
      }
    },
    "topValueChange": {
      "phasedRegistrationNames": {
        "bubbled": "onValueChange",
        "captured": "onValueChangeCapture"
      }
    },
    "topContentSizeChange": {
      "phasedRegistrationNames": {
        "bubbled": "onContentSizeChange",
        "captured": "onContentSizeChangeCapture"
      }
    },
    "topTouchCancel": {
      "phasedRegistrationNames": {
        "bubbled": "onTouchCancel",
        "captured": "onTouchCancelCapture"
      }
    }
  },
  "RCTRefreshControl": {
    "Manager": "RefreshControlManager",
    "NativeProps": {
      "tintColor": "UIColor",
      "title": "NSString",
      "onRefresh": "BOOL",
      "titleColor": "UIColor",
      "refreshing": "BOOL"
    },
    "Constants": {},
    "Commands": {}
  },
  "RCTSegmentedControl": {
    "Manager": "SegmentedControlManager",
    "NativeProps": {
      "momentary": "BOOL",
      "onChange": "BOOL",
      "tintColor": "UIColor",
      "enabled": "BOOL",
      "selectedIndex": "NSInteger",
      "values": "NSArray<NSString *>"
    },
    "Constants": {},
    "Commands": {}
  },
  "RCTSlider": {
    "Manager": "SliderManager",
    "NativeProps": {
      "maximumTrackTintColor": "UIColor",
      "onSlidingComplete": "BOOL",
      "minimumTrackImage": "UIImage",
      "onValueChange": "BOOL",
      "disabled": "BOOL",
      "value": "float",
      "thumbImage": "UIImage",
      "maximumTrackImage": "UIImage",
      "minimumTrackTintColor": "UIColor",
      "step": "float",
      "maximumValue": "float",
      "trackImage": "UIImage",
      "minimumValue": "float"
    },
    "Constants": {},
    "Commands": {}
  },
  "RCTPicker": {
    "Manager": "PickerManager",
    "NativeProps": {
      "fontSize": "NSNumber",
      "color": "UIColor",
      "textAlign": "NSTextAlignment",
      "fontWeight": "NSString",
      "fontFamily": "NSString",
      "fontStyle": "NSString",
      "onChange": "BOOL",
      "selectedIndex": "NSInteger",
      "items": "NSArray<NSDictionary *>"
    },
    "Constants": {},
    "Commands": {}
  },
  "RCTTabBarItem": {
    "Manager": "TabBarItemManager",
    "NativeProps": {
      "isTVSelectable": "BOOL",
      "systemIcon": "UITabBarSystemItem",
      "badge": "id",
      "badgeColor": "UIColor",
      "title": "NSString",
      "selected": "BOOL",
      "onPress": "BOOL",
      "renderAsOriginal": "BOOL",
      "icon": "UIImage",
      "selectedIcon": "UIImage"
    },
    "Constants": {},
    "Commands": {}
  },
  "RCTProgressView": {
    "Manager": "ProgressViewManager",
    "NativeProps": {
      "progressViewStyle": "UIProgressViewStyle",
      "trackImage": "UIImage",
      "trackTintColor": "UIColor",
      "progressImage": "UIImage",
      "progressTintColor": "UIColor",
      "progress": "float"
    },
    "Constants": {},
    "Commands": {}
  },
  "RCTText": {
    "Manager": "TextManager",
    "NativeProps": {
      "textShadowColor": "UIColor",
      "textDecorationStyle": "NSUnderlineStyle",
      "color": "UIColor",
      "letterSpacing": "CGFloat",
      "textShadowRadius": "CGFloat",
      "textDecorationLine": "RCTTextDecorationLineType",
      "isHighlighted": "BOOL",
      "adjustsFontSizeToFit": "BOOL",
      "lineHeight": "CGFloat",
      "writingDirection": "NSWritingDirection",
      "textDecorationColor": "UIColor",
      "selectable": "BOOL",
      "allowFontScaling": "BOOL",
      "textShadowOffset": "CGSize",
      "minimumFontScale": "CGFloat",
      "fontWeight": "NSString",
      "fontStyle": "NSString",
      "fontSize": "CGFloat",
      "opacity": "CGFloat",
      "fontFamily": "NSString",
      "fontVariant": "NSArray",
      "textAlign": "NSTextAlignment",
      "numberOfLines": "NSUInteger",
      "ellipsizeMode": "NSLineBreakMode"
    },
    "Constants": {},
    "Commands": {}
  },
  "RCTDatePicker": {
    "Manager": "DatePickerManager",
    "NativeProps": {
      "mode": "UIDatePickerMode",
      "timeZoneOffsetInMinutes": "NSTimeZone",
      "minuteInterval": "NSInteger",
      "date": "NSDate",
      "minimumDate": "NSDate",
      "onChange": "BOOL",
      "maximumDate": "NSDate"
    },
    "Constants": {},
    "Commands": {}
  },
  "RCTImageView": {
    "Manager": "ImageViewManager",
    "NativeProps": {
      "onPartialLoad": "BOOL",
      "capInsets": "UIEdgeInsets",
      "blurRadius": "CGFloat",
      "onProgress": "BOOL",
      "onError": "BOOL",
      "onLoadEnd": "BOOL",
      "defaultSource": "UIImage",
      "source": "NSArray<RCTImageSource *>",
      "tintColor": "UIColor",
      "onLoad": "BOOL",
      "resizeMode": "RCTResizeMode",
      "onLoadStart": "BOOL"
    },
    "Constants": {},
    "Commands": {
      "getSize": 0,
      "prefetchImage": 1
    },
    "uiViewClassName": "RCTImageView",
    "validAttributes": {
      "borderLeftWidth": true,
      "onLayout": true,
      "paddingRight": true,
      "marginRight": true,
      "shouldRasterizeIOS": true,
      "alignContent": true,
      "maxHeight": true,
      "backgroundColor": {},
      "flexGrow": true,
      "borderTopWidth": true,
      "borderLeftColor": {},
      "removeClippedSubviews": true,
      "zIndex": true,
      "marginVertical": true,
      "flexBasis": true,
      "flex": true,
      "flexWrap": true,
      "paddingBottom": true,
      "borderTopColor": {},
      "paddingTop": true,
      "justifyContent": true,
      "position": true,
      "padding": true,
      "marginBottom": true,
      "pointerEvents": true,
      "shadowColor": {},
      "top": true,
      "aspectRatio": true,
      "left": true,
      "alignSelf": true,
      "borderTopLeftRadius": true,
      "minWidth": true,
      "borderBottomWidth": true,
      "borderColor": {},
      "borderTopRightRadius": true,
      "flexDirection": true,
      "margin": true,
      "alignItems": true,
      "display": true,
      "marginHorizontal": true,
      "borderRadius": true,
      "opacity": true,
      "shadowOpacity": true,
      "right": true,
      "paddingLeft": true,
      "onAccessibilityTap": true,
      "minHeight": true,
      "direction": true,
      "borderBottomLeftRadius": true,
      "onMagicTap": true,
      "height": true,
      "accessibilityTraits": true,
      "borderWidth": true,
      "flexShrink": true,
      "paddingVertical": true,
      "shadowOffset": {},
      "accessible": true,
      "borderStyle": true,
      "borderRightColor": {},
      "overflow": true,
      "accessibilityLabel": true,
      "borderBottomColor": {},
      "paddingHorizontal": true,
      "hitSlop": {},
      "borderBottomRightRadius": true,
      "borderRightWidth": true,
      "maxWidth": true,
      "backfaceVisibility": true,
      "marginTop": true,
      "testID": true,
      "width": true,
      "transform": {},
      "accessibilityViewIsModal": true,
      "marginLeft": true,
      "bottom": true,
      "shadowRadius": true,
      "onPartialLoad": true,
      "capInsets": {},
      "blurRadius": true,
      "onProgress": true,
      "onError": true,
      "onLoadEnd": true,
      "defaultSource": {},
      "source": true,
      "tintColor": {},
      "onLoad": true,
      "resizeMode": true,
      "onLoadStart": true,
      "style": {
        "display": "display",
        "width": "width",
        "height": "height",
        "top": "top",
        "left": "left",
        "right": "right",
        "bottom": "bottom",
        "minWidth": "minWidth",
        "maxWidth": "maxWidth",
        "minHeight": "minHeight",
        "maxHeight": "maxHeight",
        "margin": "margin",
        "marginVertical": "marginVertical",
        "marginHorizontal": "marginHorizontal",
        "marginTop": "marginTop",
        "marginBottom": "marginBottom",
        "marginLeft": "marginLeft",
        "marginRight": "marginRight",
        "padding": "padding",
        "paddingVertical": "paddingVertical",
        "paddingHorizontal": "paddingHorizontal",
        "paddingTop": "paddingTop",
        "paddingBottom": "paddingBottom",
        "paddingLeft": "paddingLeft",
        "paddingRight": "paddingRight",
        "borderWidth": "borderWidth",
        "borderTopWidth": "borderTopWidth",
        "borderRightWidth": "borderRightWidth",
        "borderBottomWidth": "borderBottomWidth",
        "borderLeftWidth": "borderLeftWidth",
        "position": "position",
        "flexDirection": "flexDirection",
        "flexWrap": "flexWrap",
        "justifyContent": "justifyContent",
        "alignItems": "alignItems",
        "alignSelf": "alignSelf",
        "alignContent": "alignContent",
        "overflow": "overflow",
        "flex": "flex",
        "flexGrow": "flexGrow",
        "flexShrink": "flexShrink",
        "flexBasis": "flexBasis",
        "aspectRatio": "aspectRatio",
        "zIndex": "zIndex",
        "direction": "direction",
        "shadowColor": {},
        "shadowOffset": {},
        "shadowOpacity": "shadowOpacity",
        "shadowRadius": "shadowRadius",
        "transform": {},
        "transformMatrix": "transformMatrix",
        "decomposedMatrix": "decomposedMatrix",
        "scaleX": "scaleX",
        "scaleY": "scaleY",
        "rotation": "rotation",
        "translateX": "translateX",
        "translateY": "translateY",
        "backfaceVisibility": "backfaceVisibility",
        "backgroundColor": {},
        "borderColor": {},
        "borderTopColor": {},
        "borderRightColor": {},
        "borderBottomColor": {},
        "borderLeftColor": {},
        "borderRadius": "borderRadius",
        "borderTopLeftRadius": "borderTopLeftRadius",
        "borderTopRightRadius": "borderTopRightRadius",
        "borderBottomLeftRadius": "borderBottomLeftRadius",
        "borderBottomRightRadius": "borderBottomRightRadius",
        "borderStyle": "borderStyle",
        "opacity": "opacity",
        "elevation": "elevation",
        "color": {},
        "fontFamily": "fontFamily",
        "fontSize": "fontSize",
        "fontStyle": "fontStyle",
        "fontWeight": "fontWeight",
        "fontVariant": "fontVariant",
        "textShadowOffset": "textShadowOffset",
        "textShadowRadius": "textShadowRadius",
        "textShadowColor": {},
        "letterSpacing": "letterSpacing",
        "lineHeight": "lineHeight",
        "textAlign": "textAlign",
        "textAlignVertical": "textAlignVertical",
        "includeFontPadding": "includeFontPadding",
        "textDecorationLine": "textDecorationLine",
        "textDecorationStyle": "textDecorationStyle",
        "textDecorationColor": {},
        "writingDirection": "writingDirection",
        "resizeMode": "resizeMode",
        "tintColor": {},
        "overlayColor": {}
      }
    },
    "propTypes": {}
  },
  "Dimensions": {
    "window": {
      "width": 414,
      "scale": 3,
      "height": 736
    }
  },
  "RCTTextField": {
    "Manager": "TextFieldManager",
    "NativeProps": {
      "selectionColor": "UIColor",
      "color": "UIColor",
      "selectTextOnFocus": "BOOL",
      "text": "NSString",
      "clearTextOnFocus": "BOOL",
      "spellCheck": "UITextSpellCheckingType",
      "autoCorrect": "UITextAutocorrectionType",
      "autoCapitalize": "UITextAutocapitalizationType",
      "placeholder": "NSString",
      "secureTextEntry": "BOOL",
      "selection": "RCTTextSelection",
      "blurOnSubmit": "BOOL",
      "keyboardType": "UIKeyboardType",
      "clearButtonMode": "UITextFieldViewMode",
      "mostRecentEventCount": "NSInteger",
      "fontWeight": "NSString",
      "fontStyle": "NSString",
      "fontSize": "NSNumber",
      "onSelectionChange": "BOOL",
      "fontFamily": "NSString",
      "placeholderTextColor": "UIColor",
      "enablesReturnKeyAutomatically": "BOOL",
      "returnKeyType": "UIReturnKeyType",
      "editable": "BOOL",
      "textAlign": "NSTextAlignment",
      "password": "BOOL",
      "caretHidden": "BOOL",
      "keyboardAppearance": "UIKeyboardAppearance",
      "maxLength": "NSNumber"
    },
    "Constants": {},
    "Commands": {}
  },
  "RCTView": {
    "Manager": "ViewManager",
    "NativeProps": {
      "borderLeftWidth": "float",
      "onLayout": "BOOL",
      "paddingRight": "YGValue",
      "marginRight": "YGValue",
      "shouldRasterizeIOS": "BOOL",
      "alignContent": "YGAlign",
      "maxHeight": "YGValue",
      "backgroundColor": "UIColor",
      "flexGrow": "float",
      "borderTopWidth": "float",
      "borderLeftColor": "UIColor",
      "removeClippedSubviews": "BOOL",
      "zIndex": "NSInteger",
      "marginVertical": "YGValue",
      "flexBasis": "YGValue",
      "flex": "float",
      "flexWrap": "YGWrap",
      "paddingBottom": "YGValue",
      "borderTopColor": "UIColor",
      "paddingTop": "YGValue",
      "justifyContent": "YGJustify",
      "position": "YGPositionType",
      "padding": "YGValue",
      "marginBottom": "YGValue",
      "pointerEvents": "RCTPointerEvents",
      "shadowColor": "CGColor",
      "top": "YGValue",
      "aspectRatio": "float",
      "left": "YGValue",
      "alignSelf": "YGAlign",
      "borderTopLeftRadius": "CGFloat",
      "minWidth": "YGValue",
      "borderBottomWidth": "float",
      "borderColor": "CGColor",
      "borderTopRightRadius": "CGFloat",
      "flexDirection": "YGFlexDirection",
      "margin": "YGValue",
      "alignItems": "YGAlign",
      "display": "YGDisplay",
      "marginHorizontal": "YGValue",
      "borderRadius": "CGFloat",
      "opacity": "CGFloat",
      "shadowOpacity": "float",
      "right": "YGValue",
      "paddingLeft": "YGValue",
      "onAccessibilityTap": "BOOL",
      "minHeight": "YGValue",
      "direction": "YGDirection",
      "borderBottomLeftRadius": "CGFloat",
      "onMagicTap": "BOOL",
      "height": "YGValue",
      "accessibilityTraits": "UIAccessibilityTraits",
      "borderWidth": "float",
      "flexShrink": "float",
      "paddingVertical": "YGValue",
      "shadowOffset": "CGSize",
      "accessible": "BOOL",
      "borderStyle": "RCTBorderStyle",
      "borderRightColor": "UIColor",
      "overflow": "YGOverflow",
      "accessibilityLabel": "NSString",
      "borderBottomColor": "UIColor",
      "paddingHorizontal": "YGValue",
      "hitSlop": "UIEdgeInsets",
      "borderBottomRightRadius": "CGFloat",
      "borderRightWidth": "float",
      "maxWidth": "YGValue",
      "backfaceVisibility": "css_backface_visibility_t",
      "marginTop": "YGValue",
      "testID": "NSString",
      "width": "YGValue",
      "transform": "CATransform3D",
      "accessibilityViewIsModal": "BOOL",
      "marginLeft": "YGValue",
      "bottom": "YGValue",
      "shadowRadius": "CGFloat"
    },
    "Constants": {},
    "Commands": {},
    "uiViewClassName": "RCTView",
    "validAttributes": {
      "borderLeftWidth": true,
      "onLayout": true,
      "paddingRight": true,
      "marginRight": true,
      "shouldRasterizeIOS": true,
      "alignContent": true,
      "maxHeight": true,
      "backgroundColor": {},
      "flexGrow": true,
      "borderTopWidth": true,
      "borderLeftColor": {},
      "removeClippedSubviews": true,
      "zIndex": true,
      "marginVertical": true,
      "flexBasis": true,
      "flex": true,
      "flexWrap": true,
      "paddingBottom": true,
      "borderTopColor": {},
      "paddingTop": true,
      "justifyContent": true,
      "position": true,
      "padding": true,
      "marginBottom": true,
      "pointerEvents": true,
      "shadowColor": {},
      "top": true,
      "aspectRatio": true,
      "left": true,
      "alignSelf": true,
      "borderTopLeftRadius": true,
      "minWidth": true,
      "borderBottomWidth": true,
      "borderColor": {},
      "borderTopRightRadius": true,
      "flexDirection": true,
      "margin": true,
      "alignItems": true,
      "display": true,
      "marginHorizontal": true,
      "borderRadius": true,
      "opacity": true,
      "shadowOpacity": true,
      "right": true,
      "paddingLeft": true,
      "onAccessibilityTap": true,
      "minHeight": true,
      "direction": true,
      "borderBottomLeftRadius": true,
      "onMagicTap": true,
      "height": true,
      "accessibilityTraits": true,
      "borderWidth": true,
      "flexShrink": true,
      "paddingVertical": true,
      "shadowOffset": {},
      "accessible": true,
      "borderStyle": true,
      "borderRightColor": {},
      "overflow": true,
      "accessibilityLabel": true,
      "borderBottomColor": {},
      "paddingHorizontal": true,
      "hitSlop": {},
      "borderBottomRightRadius": true,
      "borderRightWidth": true,
      "maxWidth": true,
      "backfaceVisibility": true,
      "marginTop": true,
      "testID": true,
      "width": true,
      "transform": {},
      "accessibilityViewIsModal": true,
      "marginLeft": true,
      "bottom": true,
      "shadowRadius": true,
      "style": {
        "display": "display",
        "width": "width",
        "height": "height",
        "top": "top",
        "left": "left",
        "right": "right",
        "bottom": "bottom",
        "minWidth": "minWidth",
        "maxWidth": "maxWidth",
        "minHeight": "minHeight",
        "maxHeight": "maxHeight",
        "margin": "margin",
        "marginVertical": "marginVertical",
        "marginHorizontal": "marginHorizontal",
        "marginTop": "marginTop",
        "marginBottom": "marginBottom",
        "marginLeft": "marginLeft",
        "marginRight": "marginRight",
        "padding": "padding",
        "paddingVertical": "paddingVertical",
        "paddingHorizontal": "paddingHorizontal",
        "paddingTop": "paddingTop",
        "paddingBottom": "paddingBottom",
        "paddingLeft": "paddingLeft",
        "paddingRight": "paddingRight",
        "borderWidth": "borderWidth",
        "borderTopWidth": "borderTopWidth",
        "borderRightWidth": "borderRightWidth",
        "borderBottomWidth": "borderBottomWidth",
        "borderLeftWidth": "borderLeftWidth",
        "position": "position",
        "flexDirection": "flexDirection",
        "flexWrap": "flexWrap",
        "justifyContent": "justifyContent",
        "alignItems": "alignItems",
        "alignSelf": "alignSelf",
        "alignContent": "alignContent",
        "overflow": "overflow",
        "flex": "flex",
        "flexGrow": "flexGrow",
        "flexShrink": "flexShrink",
        "flexBasis": "flexBasis",
        "aspectRatio": "aspectRatio",
        "zIndex": "zIndex",
        "direction": "direction",
        "shadowColor": {},
        "shadowOffset": {},
        "shadowOpacity": "shadowOpacity",
        "shadowRadius": "shadowRadius",
        "transform": {},
        "transformMatrix": "transformMatrix",
        "decomposedMatrix": "decomposedMatrix",
        "scaleX": "scaleX",
        "scaleY": "scaleY",
        "rotation": "rotation",
        "translateX": "translateX",
        "translateY": "translateY",
        "backfaceVisibility": "backfaceVisibility",
        "backgroundColor": {},
        "borderColor": {},
        "borderTopColor": {},
        "borderRightColor": {},
        "borderBottomColor": {},
        "borderLeftColor": {},
        "borderRadius": "borderRadius",
        "borderTopLeftRadius": "borderTopLeftRadius",
        "borderTopRightRadius": "borderTopRightRadius",
        "borderBottomLeftRadius": "borderBottomLeftRadius",
        "borderBottomRightRadius": "borderBottomRightRadius",
        "borderStyle": "borderStyle",
        "opacity": "opacity",
        "elevation": "elevation",
        "color": {},
        "fontFamily": "fontFamily",
        "fontSize": "fontSize",
        "fontStyle": "fontStyle",
        "fontWeight": "fontWeight",
        "fontVariant": "fontVariant",
        "textShadowOffset": "textShadowOffset",
        "textShadowRadius": "textShadowRadius",
        "textShadowColor": {},
        "letterSpacing": "letterSpacing",
        "lineHeight": "lineHeight",
        "textAlign": "textAlign",
        "textAlignVertical": "textAlignVertical",
        "includeFontPadding": "includeFontPadding",
        "textDecorationLine": "textDecorationLine",
        "textDecorationStyle": "textDecorationStyle",
        "textDecorationColor": {},
        "writingDirection": "writingDirection",
        "resizeMode": "resizeMode",
        "tintColor": {},
        "overlayColor": {}
      }
    },
    "propTypes": {}
  },
  "RCTActivityIndicatorView": {
    "Manager": "ActivityIndicatorViewManager",
    "NativeProps": {
      "size": "UIActivityIndicatorViewStyle",
      "hidesWhenStopped": "BOOL",
      "animating": "BOOL",
      "color": "UIColor"
    },
    "Constants": {},
    "Commands": {}
  },
  "RCTNavItem": {
    "Manager": "NavItemManager",
    "NativeProps": {
      "backButtonTitle": "NSString",
      "leftButtonSystemIcon": "UIBarButtonSystemItem",
      "leftButtonTitle": "NSString",
      "shadowHidden": "BOOL",
      "navigationBarHidden": "BOOL",
      "titleTextColor": "UIColor",
      "backButtonIcon": "UIImage",
      "rightButtonTitle": "NSString",
      "titleImage": "UIImage",
      "tintColor": "UIColor",
      "title": "NSString",
      "translucent": "BOOL",
      "rightButtonIcon": "UIImage",
      "rightButtonSystemIcon": "UIBarButtonSystemItem",
      "onLeftButtonPress": "BOOL",
      "onRightButtonPress": "BOOL",
      "barTintColor": "UIColor",
      "leftButtonIcon": "UIImage"
    },
    "Constants": {},
    "Commands": {}
  },
  "RCTRawText": {
    "Manager": "RawTextManager",
    "NativeProps": {
      "text": "NSString"
    },
    "Constants": {},
    "Commands": {}
  },
  "RCTModalHostView": {
    "Manager": "ModalHostViewManager",
    "NativeProps": {
      "onShow": "BOOL",
      "supportedOrientations": "NSArray",
      "animationType": "NSString",
      "onOrientationChange": "BOOL",
      "transparent": "BOOL"
    },
    "Constants": {},
    "Commands": {}
  },
  "RCTWebView": {
    "Manager": "WebViewManager",
    "NativeProps": {
      "onLoadingStart": "BOOL",
      "scrollEnabled": "BOOL",
      "onLoadingFinish": "BOOL",
      "allowsInlineMediaPlayback": "BOOL",
      "source": "NSDictionary",
      "scalesPageToFit": "BOOL",
      "onLoadingError": "BOOL",
      "messagingEnabled": "BOOL",
      "decelerationRate": "CGFloat",
      "mediaPlaybackRequiresUserAction": "BOOL",
      "onShouldStartLoadWithRequest": "BOOL",
      "contentInset": "UIEdgeInsets",
      "bounces": "BOOL",
      "onMessage": "BOOL",
      "injectedJavaScript": "NSString",
      "dataDetectorTypes": "UIDataDetectorTypes",
      "automaticallyAdjustContentInsets": "BOOL"
    },
    "Constants": {},
    "Commands": {
      "goBack": 0,
      "goForward": 1,
      "reload": 2,
      "stopLoading": 3,
      "postMessage": 4,
      "injectJavaScript": 5,
      "startLoadWithResult": 6
    }
  },
  "RCTTabBar": {
    "Manager": "TabBarManager",
    "NativeProps": {
      "unselectedTintColor": "UIColor",
      "tintColor": "UIColor",
      "unselectedItemTintColor": "UIColor",
      "translucent": "BOOL",
      "barTintColor": "UIColor",
      "itemPositioning": "UITabBarItemPositioning"
    },
    "Constants": {},
    "Commands": {}
  }
}
```

**Comment by Repetitions** [comment] 2017-05-13 22:01
@xotahal @dwilt UIManager.showPopupMenu is only available on Android, so another way is needed to support iOS. One possible solution I've seen suggested would be to use a transparent modal with a styled view for the menu.

**Comment by janziemba** [comment] 2017-09-04 12:41
Duplicate of #40

**Closed** 2017-09-05 09:02 UTC
