### ISSUE TITLE
Right element menu clicks reloads the app

### ISSUE THREAD

**Issue by niksgupt** [xotahal/react-native-material-ui#315] opened 2018-03-13 19:11 UTC
Hi,

Its an amazing work. I have been trying my hands on react native since 2 weeks and I know how much works goes into making something like this.

I have following toolbar which works fine in android but its crashing in iOS. Also I am creating my app on snack,expo

    <Toolbar leftElement="arrow-back" onLeftElementPress={() => navigation.navigate('Primary', {}, { 
        type: "Navigate", routeName: "Primary",})} 
        centerElement="" rightElement={{ actions: ['archive', 'delete', 'email'], menu: { labels: ['Move to', 
        'Change labels', 'Mark as important', 'Mute', 'Print', 'Report spam'] }, }} onRightElementPress={(e) => 
         alert(e.action + ", " + e.index)} />

Seems like a bug. Not sure if any one has faced it or not.

**Comment by janziemba** [comment] 2018-03-21 10:06
Duplicate of #40

**Closed by janziemba** 2018-03-21 10:06 UTC
