### ISSUE TITLE
Toolbar Menu

### ISSUE THREAD

**Issue by RishitKedia** [xotahal/react-native-material-ui#172] opened 2017-07-22 11:06 UTC
Hey! 👋 

Thank you for this library! Much appreciated. 🙏 

Currently, the `Toolbar Menu` uses UIManager.showPopupMenu() which is available only on Android, and therefore doesn't work on iOS. 😭 

Related issues reporting the bug: #40, #131 

There's a similar package [`react-native-material-dropdown`](https://github.com/n4kz/react-native-material-dropdown) which is great, and can be used for the `Toolbar Menu`. 😉 

I've created an issue there (n4kz/react-native-material-dropdown#5) to make the dropdown menu more abstract (and untie it from the TextField) so that it can be used with the Toolbar here. 💪 

Would love to hear the community's thoughts about the best way forward here. 😃 

/cc @xotahal @n4kz 

Thanks! 👍

**Comment by 4ship** [comment] 2017-08-08 20:09
I used this library https://github.com/instea/react-native-popup-menu instead of UIManager.showPopupMenu()

**Comment by janziemba** [comment] 2017-09-04 12:41
Duplicate of #40

**Closed** 2017-09-05 09:02 UTC

**Comment by RishitKedia** [comment] 2017-10-20 21:10
## Update (for others looking for a solution)

I've managed to implement this using [`react-native-material-dropdown`](https://github.com/n4kz/react-native-material-dropdown). 🎉 

See n4kz/react-native-material-dropdown#5. 🙃
