### ISSUE TITLE
Bug: Toolbar IOS searchable icon not transparent

### ISSUE THREAD

**Issue by DevTrong** [xotahal/react-native-material-ui#121] opened 2017-03-14 21:22 UTC
**Steps to reproduce:** 

1. Add a searchable toolbar
2. Press the search button

**Expected result:** The icons should be transparent 
![image](https://cloud.githubusercontent.com/assets/3624351/23937167/608dff1a-0956-11e7-81ca-685a5152c32a.png)

**Actual result:** The icons have a colored background
![image](https://cloud.githubusercontent.com/assets/3624351/23922879/91407496-0904-11e7-8116-c0eccb308af8.png)

**Environment:** IOS

Thanks & best regards

edit: more detailed bug report

**Comment by li-zhenyu** [comment] 2017-03-14 23:20
I have the same issue but in iOS.

**Comment by DevTrong** [comment] 2017-03-15 07:12
My old bug report was a bit misleading. Updated.

**Comment by iRoachie** [comment] 2017-04-19 23:07
Same issue
![screen shot 2017-04-19 at 7 07 27 pm](https://cloud.githubusercontent.com/assets/5962998/25205993/7599d8c2-2533-11e7-87e2-d3c531653608.png)

**Comment by iRoachie** [comment] 2017-04-21 19:17
Duplicate of #96

**Comment by xotahal** [comment] 2017-05-10 12:41
Done - https://github.com/xotahal/react-native-material-ui/releases/tag/v1.10.0

**Closed by xotahal** 2017-05-10 12:41 UTC
